all:
  directory: "datasets/all"
  topics:
    - "artif_int"
    - "blockchain"
    - "cloud_comp"
    - "comp_netw"
    - "database"
    - "netw_sec"
public:
  directory: "datasets/public"
  topics:
    - "comp_netw"
    - "netw_sec"
private_1:
  directory: "datasets/private_1"
  topics:
    - "artif_int"
    - "database"
private_2:
  directory: "datasets/private_2"
  topics:
    - "blockchain"
    - "cloud_comp"