all:
  directory: "datasets/all"
  topics:
    - "artif_int"
    - "blockchain"
    - "cloud_comp"
    - "comp_netw"
    - "database"
    - "netw_sec"
  split_test: True
  # splits:
  #   - "train"
  #   - "validation"
  #   - "test"
public:
  directory: "datasets/public"
  topics:
    - "comp_netw"
    - "netw_sec"
  split_test: False
  # splits:
  #   - "train"
  #   - "validation"
private_1:
  directory: "datasets/private_1"
  topics:
    - "artif_int"
    - "database"
  split_test: False
  # splits:
  #   - "train"
  #   - "validation"
private_2:
  directory: "datasets/private_2"
  topics:
    - "blockchain"
    - "cloud_comp"
  split_test: False
  # splits:
  #   - "train"
  #   - "validation"