artif_int:
  search_query: "artificial%20intelligence"
  db_name: "courses_artif_int.db"
  json_file: "courses_artif_int.json"
  csv_file: "courses_artif_int.csv"
blockchain:
  search_query: "blockchain"
  db_name: "courses_blockchain.db"
  json_file: "courses_blockchain.json"
  csv_file: "courses_blockchain.csv"
cloud_comp:
  search_query: "cloud%20computing"
  db_name: "courses_cloud_comp.db"
  json_file: "courses_cloud_comp.json"
  csv_file: "courses_cloud_comp.csv"
comp_netw:
  search_query: "computer%20networking"
  db_name: "courses_comp_netw.db"
  json_file: "courses_comp_netw.json"
  csv_file: "courses_comp_netw.csv"
database:
  search_query: "database"
  db_name: "courses_database.db"
  json_file: "courses_database.json"
  csv_file: "courses_database.csv"
netw_sec:
  search_query: "network%20security"
  db_name: "courses_netw_sec.db"
  json_file: "courses_netw_sec.json"
  csv_file: "courses_netw_sec.csv"